baseurl         = "https://glenn.thedixons.net"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
summaryLength   = 25
NewContentEditor = "code"

[params]
  title       = "Glenn 2.0"
  subtitle    = "New! Improved! Retired!"
  copyright   = "© 2019 Glenn E. Dixon"

#  cover       = "img/blog-cover.jpg"
#  description = "Here is a description of your site."
  metaDescription = ""
#  googleAnalytics = ""
  customCSS = ["custom.css"]
  RSSLink = "https://glenn.thedixons.net/index.xml"

  twitterName = "coyotejano"
#  fbName = "fakeghost"
  microblogName = "mexpat"
  githubName = "dixonge"
  instagramName = "dixonge"
  flickrName = "djtrashy"
  mastodonName = "donblanco"
#  linkedinName = "eueung"
#  mediumName = ""

#  logo = "hugo-logo.png"
#  orgName = "Glenn E. Dixon"
#  orgWebsite = "https://www.telematika.org"
#  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Glenn E. Dixon"
  authorAvatar = "images/2018/08/avatar-grouch.jpg"
  authorLocation = "Zacatecas, Mexico"
  authorWebsite = "https://glenn.thedixons.net"
  authorDescription = "Retired I.T. nerd – Mexpat – vegan – atheist – aspirational writer, musician, genealogist"

  pageNotFoundTitle = "Oops! That page doesn't exist (404 error)"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  blog = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

#[[menu.main]]
#  name = "The Real Glenn"
#  url = "/the-real-glenn"
#  weight = 197

[[menu.main]]
  name = "Code Snippets"
  url = "/code-snippets"
  weight = 195
  
[[menu.main]]
  name = "Posts"
  url = "/tags/posts/"
  weight = 190

[[menu.main]]
  name = "Notes"
  url = "/tags/notes/"
  weight = 189

[[menu.main]]
  name = "Replies"
  url = "/tags/replies/"
  weight = 188

[[menu.main]]
  name = "Pics"
  url = "/tags/pics/"
  weight = 187

[[menu.main]]
  name = "Vids"
  url = "/tags/vids/"
  weight = 186

[[menu.main]]
  name = "Links"
  url = "/tags/links/"
  weight = 185

[[menu.main]]
  name = "Exercise"
  url = "/tags/exercise/"
  weight = 183

[[menu.main]]
  name = "Quotes"
  url = "/tags/quotes/"
  weight = 181

[[menu.main]]
  name = "Books"
  url = "/tags/books/"
  weight = 180

[[menu.main]]
  name = "All Tags"
  url = "/tags/"
  weight = 100

[[menu.main]]
  name = "All Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 98
